import { Sour_Gummy, Outfit, Prata } from "next/font/google";
import "./globals.css";
import Navbar from "@/component/Navbar";
import Footer from "@/component/Footer";


const sourGummy = Sour_Gummy({
  variable: "--font-sour-gummy",
  subsets: ["latin"],
});

const outfit = Outfit({
  variable: "--font-outfit",
  subsets: ["latin"],
});

const prata = Prata({
  variable: "--font-prata",
  subsets: ["latin"],
  weight:"400"
});

// export const metadata = {
//   title: "Mash-Dev | DSA Smashers",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">

      <body
        className={`${sourGummy.variable} ${outfit.variable} ${prata.variable} antialiased`}
      >
        <title>code365 | DSA Smashers</title>
        <Navbar/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
